language: python

sudo: false   # use container-based infrastructure

python:
  - "3.4"
  - "3.5"

addons:
    apt:
        packages:
            - gfortran
            - libblas-dev
            - liblapack-dev
            - libqt4-dev

cache:
    apt: true   # does not work for public repos
    directories:
        - $HOME/.cache/pip
        - $HOME/.ccache
        - $HOME/nltk_data

before_cache:   # prevent logs from caching
    - rm -f $HOME/.cache/pip/log/debug.log

before_install:
    - pip install -U setuptools pip wheel
    - pip install codecov

install:
    - travis_wait source $TRAVIS_BUILD_DIR/travis/install_orange.sh
    - travis_wait pip install -r requirements.txt
    - source $TRAVIS_BUILD_DIR/travis/nltk_download.sh

script:
    - coverage run setup.py test

after_success:
    - codecov

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start